2017-12-14 23:03:24,010 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/fb95eff210b39d5b58abf1ef097459b0dac5d9ed/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="fb95eff210b39d5b58abf1ef097459b0dac5d9ed" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:03:40,007 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/3095b419595890ef795d2118f8566e2f227a4c9a/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="3095b419595890ef795d2118f8566e2f227a4c9a" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:04:44,346 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/34ac497a39b4a2f7754a5ac1074cb3d37ad85ea0/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="34ac497a39b4a2f7754a5ac1074cb3d37ad85ea0" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:04:49,350 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/31498525e678a7d4f012d6c5227beec81ec2913d/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="31498525e678a7d4f012d6c5227beec81ec2913d" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:04:55,908 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/315d76ef47f38dec5945fec546837b8817f117d8/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="315d76ef47f38dec5945fec546837b8817f117d8" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:06:16,041 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/1f880237fa1debc55525403952559837a8313d80/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="1f880237fa1debc55525403952559837a8313d80" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:27:09,360 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/af139e1323ffeddd3a3563ba2dda668bf548597e/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="af139e1323ffeddd3a3563ba2dda668bf548597e" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:31:02,511 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/3973722320b5880584c6e54d93d2a12ffd7b42c0/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="3973722320b5880584c6e54d93d2a12ffd7b42c0" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:31:17,826 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/906efa0b84d40258a0d382cf874d2cb192c65deb/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="906efa0b84d40258a0d382cf874d2cb192c65deb" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:57:56,470 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/94edb28b4db20c0fe63b3ee00344652da03b198d/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="94edb28b4db20c0fe63b3ee00344652da03b198d" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-14 23:59:27,395 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/75deebfb72877e815ed90ab7d57244e4f1105d6d/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="75deebfb72877e815ed90ab7d57244e4f1105d6d" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 00:00:16,162 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/da990ac356a97e4d06315c62359babc3ce5b032f/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="da990ac356a97e4d06315c62359babc3ce5b032f" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 00:01:09,535 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/b2be80db9450356526ea08df46da57e8c4578f89/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="b2be80db9450356526ea08df46da57e8c4578f89" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 00:01:23,993 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/e877ec54445a7c17720661384b6a4be1051af93c/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="e877ec54445a7c17720661384b6a4be1051af93c" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 00:01:53,529 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/b6c02a956247e770d3e4292625fd1c4530b3124b/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="b6c02a956247e770d3e4292625fd1c4530b3124b" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 05:30:10,602 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/bbe51b1e18e2ef67e8aeecf1aa86fa7d75dfefe5/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="bbe51b1e18e2ef67e8aeecf1aa86fa7d75dfefe5" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 06:24:28,593 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/b656df69bbb6d18c6f29396e40bc28ccb2135c6c/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="b656df69bbb6d18c6f29396e40bc28ccb2135c6c" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 07:19:03,675 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/9c8fd0b04483b3e675419de5816516b4c989e7aa/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="9c8fd0b04483b3e675419de5816516b4c989e7aa" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 07:19:07,092 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/af9b8fbc40276b6792399be9fb3b27b35b9f16e0/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="af9b8fbc40276b6792399be9fb3b27b35b9f16e0" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 07:19:41,364 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/41a5b3a26b53a434d646f282529e7cf18011f043/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="41a5b3a26b53a434d646f282529e7cf18011f043" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 07:21:24,416 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/f1dc0b57cc762049b42d51898d88da1970bc2af3/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="f1dc0b57cc762049b42d51898d88da1970bc2af3" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 10:01:16,765 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/9a994a54d97fde6004ce0ed44bd23e415381e3cf/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="9a994a54d97fde6004ce0ed44bd23e415381e3cf" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 10:25:39,596 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/d5a29cd778be2bcfdcff32c6aa6b3df39a8e888c/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="d5a29cd778be2bcfdcff32c6aa6b3df39a8e888c" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 14:07:44,600 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/60c9771ea72555e12eeb007967b6cd2d18a29f9b/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="60c9771ea72555e12eeb007967b6cd2d18a29f9b" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 14:20:30,094 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/924296bd9721a6db2e10ffb753cf7fcc502ed64d/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="924296bd9721a6db2e10ffb753cf7fcc502ed64d" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:19:14,880 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/feec1b26ce7c967c6bd7331bfba1c3e16e8e3adb/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="feec1b26ce7c967c6bd7331bfba1c3e16e8e3adb" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:19:25,358 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/37c14f8372691cda89d64740a4775aecdbc2faed/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="37c14f8372691cda89d64740a4775aecdbc2faed" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:19:39,943 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/52d668e37b0cc9868381df9f636ad558933f7bf6/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="52d668e37b0cc9868381df9f636ad558933f7bf6" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:22:15,783 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/7e1f2cfca09e11e77c608c1bd0ac9d9c35c2d1df/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="7e1f2cfca09e11e77c608c1bd0ac9d9c35c2d1df" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:22:21,287 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /login/
2017-12-15 15:22:44,323 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/bc67ef26d70712fd68e46136b371ca967907f501/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="bc67ef26d70712fd68e46136b371ca967907f501" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:23:04,453 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/8b0c5bf708f44a093f12e658df04bb67e151653e/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="8b0c5bf708f44a093f12e658df04bb67e151653e" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:23:15,643 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/ee2ed1604961ce8ea2ea83a06a679603df70fb99/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="ee2ed1604961ce8ea2ea83a06a679603df70fb99" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:23:30,379 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/03d54e4d8aacef42d7d6f4caf6dcad52d7288df5/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="03d54e4d8aacef42d7d6f4caf6dcad52d7288df5" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:23:56,455 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /register/
2017-12-15 15:26:30,629 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/8e9bf88e62bbe6a8b3de5eb9562055cb2d44a910/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="8e9bf88e62bbe6a8b3de5eb9562055cb2d44a910" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:26:45,208 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/1acca29d0409efcc0cb3c9fe738e954d3ab396ef/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="1acca29d0409efcc0cb3c9fe738e954d3ab396ef" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:27:22,210 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /register/
2017-12-15 15:33:11,425 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/fc92bb0d558d9f40397e8d7d35d039d6d3e08ff7/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="fc92bb0d558d9f40397e8d7d35d039d6d3e08ff7" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:33:22,699 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/6b0ae2b59024c365a8f8459171aa1f49e19bf049/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="6b0ae2b59024c365a8f8459171aa1f49e19bf049" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:33:54,058 [ERROR] django.request: Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/edure/edure/views.py", line 250, in register
    email_send.delay(subject, email, msg, fr=settings.ADMIN_EMAIL, title='EduRe')
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/celery/app/task.py", line 555, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/kombu/connection.py", line 382, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/kombu/connection.py", line 250, in connect
    return self.connection
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/kombu/connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/kombu/connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2017-12-15 15:35:14,067 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/8f42966682d30e6980a04fc870adc05b04c5526e/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="8f42966682d30e6980a04fc870adc05b04c5526e" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 15:36:19,230 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/e5ca6b02f18a0ffeafa8475bab7c67a1f7eec62c/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="e5ca6b02f18a0ffeafa8475bab7c67a1f7eec62c" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 16:57:56,955 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/d8c7caf5d09f3766c2ef35e88c97ff8a84baee9c/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="d8c7caf5d09f3766c2ef35e88c97ff8a84baee9c" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 17:02:15,933 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/a2d8111310ef3aaca239b16641cb71f20d702404/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="a2d8111310ef3aaca239b16641cb71f20d702404" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 17:03:32,302 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/5dd6b9ce2f672ab902cbebf9ad8d1ee9a1327e70/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="5dd6b9ce2f672ab902cbebf9ad8d1ee9a1327e70" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 17:03:35,489 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/7fe9300c5d98096d8e7ec916497f18e61f16109d/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="7fe9300c5d98096d8e7ec916497f18e61f16109d" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-15 20:18:07,598 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/5ec8e5588b98e088e6cc4c687ff42412956cd315/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="5ec8e5588b98e088e6cc4c687ff42412956cd315" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 12:00:47,900 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/f6455fda0525f22815d8a05c0d8108e934341f7e/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="f6455fda0525f22815d8a05c0d8108e934341f7e" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 12:01:04,306 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/2790adcf8168e927faf13133a1349c416d60bf1a/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="2790adcf8168e927faf13133a1349c416d60bf1a" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 12:01:59,336 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /register/
2017-12-16 12:02:02,982 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/753e0fcd9c5f2a7c7ab0eb7fb0bc57bf3cc6bce5/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="753e0fcd9c5f2a7c7ab0eb7fb0bc57bf3cc6bce5" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:36:37,155 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/a3597fb1921d998affd3399c4dd684225fdf0070/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="a3597fb1921d998affd3399c4dd684225fdf0070" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:36:37,156 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/4fb98ee9f17124e7c901f5f02000c2f4f5af21b3/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="4fb98ee9f17124e7c901f5f02000c2f4f5af21b3" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:36:45,141 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/72ced5898bd4079c1d7db51300c1fbbfa1efcbf3/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="72ced5898bd4079c1d7db51300c1fbbfa1efcbf3" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:37:14,342 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/4120ab2b30eff05fa7471bde1a88b99bcdb64c9a/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="4120ab2b30eff05fa7471bde1a88b99bcdb64c9a" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:37:34,345 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/4360ee2c6832343e61c0f0e47e0827feb28013ed/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="4360ee2c6832343e61c0f0e47e0827feb28013ed" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:37:51,761 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/0448902ccec8a061391d78349fa582ccf7c00daf/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="0448902ccec8a061391d78349fa582ccf7c00daf" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:37:51,910 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/6eb7a84d7fb0e382742cf8e2cd907bc96bd89252/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="6eb7a84d7fb0e382742cf8e2cd907bc96bd89252" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:38:03,271 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/d45eae24f7f59e79a92cee11070caf38664c34f0/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="d45eae24f7f59e79a92cee11070caf38664c34f0" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:38:04,723 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/2e3bb96edcc0e6b5274268415098b7bea66f1d53/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="2e3bb96edcc0e6b5274268415098b7bea66f1d53" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:38:07,603 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/046226a156a47a6a824ea3fb3ead131b70f7056e/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="046226a156a47a6a824ea3fb3ead131b70f7056e" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:38:14,383 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/2f3cbd2a0011828a1636031d6b30e970dcaf432a/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="2f3cbd2a0011828a1636031d6b30e970dcaf432a" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:38:36,851 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/a992a65bbe15f66f2336234ea052e681cccb18d5/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="a992a65bbe15f66f2336234ea052e681cccb18d5" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:39:39,088 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/65c9d74322ecb660519af250e68311b9d8ed60ec/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="65c9d74322ecb660519af250e68311b9d8ed60ec" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-16 20:44:56,604 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/258468c7676f2f1071eee663bd515d153f70bafc/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="258468c7676f2f1071eee663bd515d153f70bafc" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-17 15:54:06,617 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2017-12-17 15:54:18,877 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2017-12-18 01:35:55,152 [WARNING] django.request: Forbidden (CSRF cookie not set.): /command.php
2017-12-18 11:02:28,135 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/6346904f2556e3aaa87b0a58fc642bd0574e5d08/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="6346904f2556e3aaa87b0a58fc642bd0574e5d08" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-18 17:48:02,982 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 17:48:02,983 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 17:48:02,983 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 17:48:02,985 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNTk3NjgyLCJpYXQiOjE1MTM1OTQwODJ9', 'WKb8c134p0kJfz3D-KujdtEa2WhR0zuQAZgFNL8rjYREp76M3A1PgA8E42FmpmMZcfpwgsgyrKl9cYLYLD2cZ_o1jP_MGadSZSh1AOEqK_syevk-ZyB5vWU__P4-3xPpZJHDzPKMcTG62ijF9dzf2ub57jphnOrDd5wtohBc9KVTMy6IA0RFYgWuGNxUnIZ8BQSdZ6XCnJ3den_hNtrEymuZ2r7Kc0GH0f_JSjRsH2CcUeQXc1kCSaX95qu3Jj4NK1TnBXc5rJUkvNaCmrhxavJak6W7fR6hJ76bhXulGfmeMslMqk5Zdfl8VElWSv5mhbXtrpBkTltsw6t3BHYTEw']
2017-12-18 17:48:02,985 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 17:48:09,667 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 17:48:09,668 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 17:48:09,668 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 17:48:09,670 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNTk3Njg5LCJpYXQiOjE1MTM1OTQwODl9', 'A-h8zZgBy2NhGxlD_9LQKfzbYS3ebsQVtKUcVR8MRKfn1EL5wL_LnL3nKkwp9bwpj8ZCralaraEOvyz5b6FEISvu2974NBMSduC78IHXj1SR2lEeUFjdn9sFaciJxzcYRzvCCFVPxjpInZTgLEKRxCgRsFAngAjXtsjG-jxtJJiBxs-3pDR20Up3i7hJ4MMJGxxQ6HFMShHJKZHTKceWfLTWFOUa7kPq1KFVi0KJFWkRta537kG5Zv9f_4QEG_FG4M3oPMqk8z8EN8sJ-Plc9dj5RRcG7CeNIpHcolY07Xj_kGsti7ql0huzIuyXZ0JXXWgX_M6rUShvl5-QX8YD9w']
2017-12-18 17:48:09,670 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 17:48:10,302 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 17:48:10,302 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 17:48:10,302 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 17:48:10,304 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNTk3NjkwLCJpYXQiOjE1MTM1OTQwOTB9', 'dcmxCvZaNV2WcRtTYI5jh1-7VD4b2vjtJyhxoMH0iKAcZwnhHm25u_X_cippbjIUeznp4Vq0RtFhAOk5UL_NY9z0M79gqFY1t5nyUtHlmP3pM6VkFYFjclM-XLSlqPP7foYwiMt8U4INyKh3OVz7kgopUo8fxiTr5ePtejgxcz_eI5qBnPAz2Jlj2PPiKeSTTdmVi6OUUEuZF56w528XMwZQPSTqpUKjsBk61oLhLDNHo7N88biXwRTZ4x0VYVO-WuoKS0oxFyScSyxy2FVkMEZFdec4NLeob2IS0aVpBS21cZVx2ecWsT71xtgnIJCPCjdiH7iDuZyUdNH7n8tf4g']
2017-12-18 17:48:10,304 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 17:48:44,438 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 17:48:44,439 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 17:48:44,439 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 17:48:44,440 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNTk3NzI0LCJpYXQiOjE1MTM1OTQxMjR9', 'kbSLRAUcuwnK68ljnv3RljjPVW4nChi_mqmAU6h5UE_-51Ovczxkem4LE1roGGq29XCDiL9Rl_n-CfsWF82nnNLb06u9X_-96C4Fdo4jwHXNcdtxfn2GE5i8HV1DuMJ28QVxFXDcnZJKy_3lIFZZs5xy3Jxtj_jMAU9az7-s0llvd85rDL-LNCx-d7ZE7L_Z8AykGfhWzo15B8kq0IG7Y_G_NpUJfAy1BnL8L0OHDx0h1mnlRsuc6kAx5j0OkXdYp-GIVg5DOd9YFdTr5co-UfIAAlSR5qxZhlIgSwVILIow1nxArwT8ZjptZ5Ev9SD9NiM_Xu-vOJ5PPnCXdDBZug']
2017-12-18 17:48:44,441 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 17:49:46,382 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 17:49:46,383 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 17:49:46,383 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 17:49:46,385 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNTk3Nzg2LCJpYXQiOjE1MTM1OTQxODZ9', 'Dqetta26iDcEIRi7cxxV0AeZ8CDSLo305q93Hdgsx6BTQrnsDSM1ssbVZeQVgoZ6aCdpI2YXUZQLbE40Vyh_X0zq8vXOPrFwWA6gwAYUWlNhLWEe8nx2CEwaTc4OIRO3fqRH80-MYVoQ20rhTA-CIOrllUq_0cWK-M9D1ELDM3ZcP2dfyf4r7i_GtwiQcCZG35HD-tn7fRRg-YtVgxmmM4y2N2US8V0xnF00DTS8JtbNx-jupbc4QDePPWfZMEXQopA7D0odqS4QbMBJgFkVfc9_E5QuC5rOk7soN7UydLS3VUCqMlvvHoqdfmViA66QTu7RAJ6mvQMr6jjAh2RyDw']
2017-12-18 17:49:46,385 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 17:49:46,466 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 17:49:46,466 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 17:49:46,466 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 17:49:46,468 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNTk3Nzg2LCJpYXQiOjE1MTM1OTQxODZ9', 'Dqetta26iDcEIRi7cxxV0AeZ8CDSLo305q93Hdgsx6BTQrnsDSM1ssbVZeQVgoZ6aCdpI2YXUZQLbE40Vyh_X0zq8vXOPrFwWA6gwAYUWlNhLWEe8nx2CEwaTc4OIRO3fqRH80-MYVoQ20rhTA-CIOrllUq_0cWK-M9D1ELDM3ZcP2dfyf4r7i_GtwiQcCZG35HD-tn7fRRg-YtVgxmmM4y2N2US8V0xnF00DTS8JtbNx-jupbc4QDePPWfZMEXQopA7D0odqS4QbMBJgFkVfc9_E5QuC5rOk7soN7UydLS3VUCqMlvvHoqdfmViA66QTu7RAJ6mvQMr6jjAh2RyDw']
2017-12-18 17:49:46,468 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 17:50:29,553 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/b482930e34c92302a48313033a85d041ac9512c6/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="b482930e34c92302a48313033a85d041ac9512c6" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-18 18:01:02,139 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 18:01:02,140 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 18:01:02,140 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 18:01:02,146 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNTk4NDYyLCJpYXQiOjE1MTM1OTQ4NjJ9', 'aeHvwcm9xfMw6ownkwG66UyggQuVOjRMXIp6k1ii7VKs8lIGA-zXraFRuSzZ-WAQsIA8tZxV6REOUIOgckcfsbDc-cSZt3NaBVUJr0k_n2eQrDuO_g1JRc9dtHVk_Y3WJy5Vbxw-K2jbAiZBIkYSx3eieXtvsCWf0ougQAgN9t7vL9VgR0oIOzZczRSYUstr9XDvuOo1FFrO0izET7C0F12nAEIOPy1-TDnhcffAsV3cLLg3bYEfg_1u1Uv2PMIHbRHcWJXIA7LmuX3rhqXPgSW8O8WKoiO_4RCWLMpJsWTtQs7UtXj8LXq06Bbjdtp5qezIBFmAvLOFIei3lsOs-Q']
2017-12-18 18:01:02,146 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 18:01:02,203 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 18:01:02,204 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 18:01:02,204 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 18:01:02,205 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNTk4NDYyLCJpYXQiOjE1MTM1OTQ4NjJ9', 'aeHvwcm9xfMw6ownkwG66UyggQuVOjRMXIp6k1ii7VKs8lIGA-zXraFRuSzZ-WAQsIA8tZxV6REOUIOgckcfsbDc-cSZt3NaBVUJr0k_n2eQrDuO_g1JRc9dtHVk_Y3WJy5Vbxw-K2jbAiZBIkYSx3eieXtvsCWf0ougQAgN9t7vL9VgR0oIOzZczRSYUstr9XDvuOo1FFrO0izET7C0F12nAEIOPy1-TDnhcffAsV3cLLg3bYEfg_1u1Uv2PMIHbRHcWJXIA7LmuX3rhqXPgSW8O8WKoiO_4RCWLMpJsWTtQs7UtXj8LXq06Bbjdtp5qezIBFmAvLOFIei3lsOs-Q']
2017-12-18 18:01:02,206 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 18:01:23,029 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/ed0eab1fe7c29c42fc9a57b07ff338e1bb7ce54f/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="ed0eab1fe7c29c42fc9a57b07ff338e1bb7ce54f" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-18 18:59:59,730 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 18:59:59,731 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 18:59:59,731 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 18:59:59,732 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNjAxOTk5LCJpYXQiOjE1MTM1OTgzOTl9', 'B7u76OZOMMMINf4HIZ_poSOI-mryfqTxANByNY_5U2kgx9OtXlOCS3AtJsg0JnZdSrYBTm3Zgi7Xsui8-s9PjwWLhHtMINFJGLrBO1KVg0hQbAgDeK-qCChOUrx4t1dYGUPxSeug-_qrrIRl_6ZNv1PRV4GRG239h1sjpBaIcRkUWNmHrWIMObj7FdoPUV8owsESNTlj75v31mYC3BQrzNKe5IHcJU6gvFVDgdLN1ftLID2IEyC4ws6igl1743L1ctB4rRf1IHiWwxg0XR1Rstu1ydZ6B72hYJMqmayOxWOZ4P-YhhZayTg7t4FdAoU9D-PKfy_LCVIO1DOilaoS_A']
2017-12-18 18:59:59,732 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 18:59:59,736 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 18:59:59,736 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 18:59:59,737 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 18:59:59,739 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNjAxOTk5LCJpYXQiOjE1MTM1OTgzOTl9', 'B7u76OZOMMMINf4HIZ_poSOI-mryfqTxANByNY_5U2kgx9OtXlOCS3AtJsg0JnZdSrYBTm3Zgi7Xsui8-s9PjwWLhHtMINFJGLrBO1KVg0hQbAgDeK-qCChOUrx4t1dYGUPxSeug-_qrrIRl_6ZNv1PRV4GRG239h1sjpBaIcRkUWNmHrWIMObj7FdoPUV8owsESNTlj75v31mYC3BQrzNKe5IHcJU6gvFVDgdLN1ftLID2IEyC4ws6igl1743L1ctB4rRf1IHiWwxg0XR1Rstu1ydZ6B72hYJMqmayOxWOZ4P-YhhZayTg7t4FdAoU9D-PKfy_LCVIO1DOilaoS_A']
2017-12-18 18:59:59,739 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 20:21:15,086 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 20:21:15,086 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 20:21:15,087 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 20:21:15,088 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNjA2ODc1LCJpYXQiOjE1MTM2MDMyNzV9', 'r9dKxY5FAJtCbqgFff5PxWSsAVrPWo073vCWrEDEo08hePfZ8oB0kXJWuuMrOOz43L9aNQdud9TYW7jv7ufNPsmlf0ABfq-U_bSW2DMcZ4WVjyKw-ugnyyOn2DuRnvRwcM50IX3jIOaLj-lBlTzwD3x4rD79YR2dZCALgmF6ETQrp4ywv50E32NBUm-ELaojJzfhHFDy0c-vhzP0hFvQn-MNLdYiN9S1XEFIvAHtyVbxdDk0VY2gO4BCDfozJed0kS_QyfdkHjKTObSmbCV9kk9AJu1Ye9rQnnfWcqpsiJ3-eSu_68EkdUhNPYzNzTjyOVBOXw0U3_jg2cR22G8_ug']
2017-12-18 20:21:15,088 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 20:21:15,152 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 20:21:15,153 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 20:21:15,153 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 20:21:15,158 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNjA2ODc1LCJpYXQiOjE1MTM2MDMyNzV9', 'r9dKxY5FAJtCbqgFff5PxWSsAVrPWo073vCWrEDEo08hePfZ8oB0kXJWuuMrOOz43L9aNQdud9TYW7jv7ufNPsmlf0ABfq-U_bSW2DMcZ4WVjyKw-ugnyyOn2DuRnvRwcM50IX3jIOaLj-lBlTzwD3x4rD79YR2dZCALgmF6ETQrp4ywv50E32NBUm-ELaojJzfhHFDy0c-vhzP0hFvQn-MNLdYiN9S1XEFIvAHtyVbxdDk0VY2gO4BCDfozJed0kS_QyfdkHjKTObSmbCV9kk9AJu1Ye9rQnnfWcqpsiJ3-eSu_68EkdUhNPYzNzTjyOVBOXw0U3_jg2cR22G8_ug']
2017-12-18 20:21:15,158 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 22:00:26,604 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 22:00:26,604 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 22:00:26,604 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 22:00:26,606 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNjEyODI2LCJpYXQiOjE1MTM2MDkyMjZ9', 'FXIK3obJTCRdiv1F5ilktm6Br1Zvd0v8M5x7GkZPoP0YZHU9-ATr6ldKGU6o2xFEZqw9M2s9SKdgtCkpE_z_VoVCc-v9iN-azMXyye2Bmd3zndsxrVNKBpel_0dw-5mYHpsCMATRL30kS-Spnlx_QUw9C9ihy4JaI5zLuDhxvabPy0O4_74vWQJ3hPtfwRgLBoKERXzCDgpeOMOtA-JYM3PTyLnB898r-lo2ILKQ91lF6ATDb02J2e3cdpJXSej9ZwfhX2OuK6BiigYS39sDakyct1NNL47Ui87YI6gxi_dsrFeHkifJ0-M1AR-eB3oEl2kExxPVr5FKzNANTHJI7Q']
2017-12-18 22:00:26,606 [INFO] oauth2client.client: Refreshing access_token
2017-12-18 22:00:31,425 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-18 22:00:31,425 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-18 22:00:31,425 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-18 22:00:31,427 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNjEyODMxLCJpYXQiOjE1MTM2MDkyMzF9', 'l5fR6-PNgdqQ6gkjqiptJcreyl8atXHKGxTkrDUNHEgkQtFsOVNff9kIZ7zr5N4dFDVo7TYV3zrwK-7F1blqZf1KqQvXTdLGZBTJ3yNgc0nHoCthwEUwlirStwyBlh9vmQhCH-EgDYXi_OaWbGLW5_Tl1uvvMfysuT_oK4c16_ud5SxX77RSZUgnuBhcA8Z6_mPSmuUPWQHN1PHidaZmDsIXrajQlrOFVodqnjLdxoKThoqBlF2UdT8Rs_xh07peWsAuGiJfek8p3FAQO9Le4j0qfqajxxRA2RkKZfMyinvh2B7hrxJXf458C7btrPTQAlGvjRgOJZ7XMarx3lV5tw']
2017-12-18 22:00:31,427 [INFO] oauth2client.client: Refreshing access_token
2017-12-19 00:31:19,297 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/eb5260d4e173036f50d66549acb119f7d0cc9523/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="eb5260d4e173036f50d66549acb119f7d0cc9523" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-19 00:32:12,095 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /register/
2017-12-19 00:32:15,282 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/adbfa39873b53d0e948540eff722adfa1823a6da/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="adbfa39873b53d0e948540eff722adfa1823a6da" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-19 00:32:40,404 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/025cc5a61aad9baa38582aea77be9da85c79b675/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="025cc5a61aad9baa38582aea77be9da85c79b675" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-19 00:32:45,154 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/7eb1e8465580b391655c374fa031b9b300709e27/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="7eb1e8465580b391655c374fa031b9b300709e27" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-19 00:40:35,126 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/d4746299a27f095153701cddf8b87bfb83f60596/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="d4746299a27f095153701cddf8b87bfb83f60596" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-19 16:31:29,537 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-19 16:31:29,538 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-19 16:31:29,538 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-19 16:31:29,540 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNjc5NDg5LCJpYXQiOjE1MTM2NzU4ODl9', 'qwFrvPHzh_kfUMS4QxmGnwB0lfNZyCmRmMzMARBcNip1jIRF5zQ3glivRjJBxh4CajDb2CANZZ1V66BPNTQ2lLpHEg0VFdWsozIJLRmc4_vc0EOBUutx1kJKumRTPU3T_lC701JFeCu_H9ciNL2oWhlr57nPVmWxroDeCHfZXMu3UST8JuoEW9E5zWQAshHjAY8CaJqBa9mGFg0T-Z7C80CTR_zoL5g-aNObACxJ0puBNLvsSsqcFuLmobu58dGm7pGuZJkifqBCIgcLFKQ_l7BQrjDyEcdzAtGUliUE0OxM52bDOsh_wY851z2GQP4oAw6ofSOEWDhjXG0dBZPqKQ']
2017-12-19 16:31:29,540 [INFO] oauth2client.client: Refreshing access_token
2017-12-19 17:22:49,940 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/47b3a512d15c01d4055e58a0227110e9a7301bf7/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="47b3a512d15c01d4055e58a0227110e9a7301bf7" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-19 17:23:08,624 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/1c510bb2b1c1855c9af433db7170bc35e307b487/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="1c510bb2b1c1855c9af433db7170bc35e307b487" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-19 18:03:04,414 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/5b05a590db7b93dcc7af9dc73e2eebb50528786d/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="5b05a590db7b93dcc7af9dc73e2eebb50528786d" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-19 18:09:56,436 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/29b7e3450fa8713c8e0811875f6e2f897e0a6207/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="29b7e3450fa8713c8e0811875f6e2f897e0a6207" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-19 18:11:35,438 [DEBUG] taaruf: CAPTCHA content: <tr><th><label for="id_captcha_1">Captcha:</label></th><td>
<img src="/captcha/image/d16d1f7b19cfad2219545d28e762e99dec63c4f4/" alt="captcha" class="captcha" /><input id="id_captcha_0" name="captcha_0" type="hidden" value="d16d1f7b19cfad2219545d28e762e99dec63c4f4" />
<input autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" id="id_captcha_1" name="captcha_1" type="text" />

</td></tr>
2017-12-20 15:53:21,429 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-20 15:53:21,431 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-20 15:53:21,431 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-20 15:53:21,434 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNzYzNjAxLCJpYXQiOjE1MTM3NjAwMDF9', 'iIKbXYVzmXr1APnHWEZy6WEwowr5AbmPm-srNOJ5Pxje1vLhOCGb-FP-UveZvx9wtNx-UX2tvcZw9FRVo9WHa6Q7toTe4Yad8ccXe8unrJqPsl_yVLjiEirwT2RRf8YxrYFh0EGpqi-eqAP653R07qqKzcFGzJ-6H5eF2gtPF1oEfyQG77W7qCb0ka_fYvE0bEyQgHsUpIU0f4yo_anhjwrE1WW9I-KvFpnSlXaNfxH9CAakBZb2GtKm6lLh_KuraCoR2741BirhrZacaH304kJ-hN6nLvwivkDUtQiqVEE03TyehfKgfzM2Z43McpixfCrmuSGQcfT6FZ0dTEc9vQ']
2017-12-20 15:53:21,434 [INFO] oauth2client.client: Refreshing access_token
2017-12-20 15:53:26,379 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-20 15:53:26,380 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-20 15:53:26,380 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-20 15:53:26,382 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzNzYzNjA2LCJpYXQiOjE1MTM3NjAwMDZ9', 'lq5Y9cba6dgh0khniZ_X0UTJ5tkXjRU8dUV82uPZzh8hEgtXWL_uc79VZi24V_xUavwqv_nmTgNFaqwcNKDXfL5zJKbJTB2Y8rozYHUpPsXh1iuqpJDtnVB3QnkrMNvl2H8JXFvgSvJDFNco03OGPS2Qh7fzqoqi3T_21S28UJgTuLTvvUeciIXIrT357stNIpP1OcP2jrMjl7R_nOxeZQV16yosXMRJR5bhDU9t8y09eIR0UFSG7GTjPph970EK2L_2q1mVdCjb4YlRZvL0DG8n7L9AW3S5tG3fS76sOjt_5VymTYq6PRyUw4kYh1fdgMuszN55QYUZ_OO-kWlWlg']
2017-12-20 15:53:26,382 [INFO] oauth2client.client: Refreshing access_token
2017-12-21 11:29:06,389 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-21 11:29:06,389 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-21 11:29:06,390 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-21 11:29:06,391 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzODM0MTQ2LCJpYXQiOjE1MTM4MzA1NDZ9', 'F3YrwqQEq3Pjw7nYGjG1V37mIZ4mbBMDjfH9v7NxMViJ5TXbNZf3-lHhJ44umcljvEHB8EbVnIHZvJlUMDhCfBLnLcJLWZfL1jCC4LKFhUkXWdnDrRFkcrj5bj9I0plZ9SQWbX8q62V091GHg1mazF0SFPRW1kIysE4lbpgXTMAN13cls0ng3s0UOuzWFYkzSS1toEKDtF7wjKE_g0IITDiT39KGHHS7qp0dlu8Eg6KSdgtbAzmPjjSV3dznHh2eX1T6eW-AvwC39-vBFedFL3GAljGS8HHe5heN7byH1H_xbIEf7N9YVxceKtZmA-cSLgZiJCL1PiPr3ZKcLuH7mg']
2017-12-21 11:29:06,392 [INFO] oauth2client.client: Refreshing access_token
2017-12-21 11:29:11,259 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-21 11:29:11,260 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-21 11:29:11,260 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-21 11:29:11,262 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzODM0MTUxLCJpYXQiOjE1MTM4MzA1NTF9', 'UVS8uMr6C-7JNxTQn_8yyYc7675t7I8OQRRoKM7rHNG3pZtArbeTkVH1hIbf09-50aCRqNhSg4WyIZMz8L-CnnjIJ8OKED9x-sCTKVIAW8qhmpVDTVpjRKqGpGGt7EGRsrClefsx5JAtodUjjXj05JJrc7sTccjhNlRGiR210qcpRTZMEP_Q-Yy7BAEECm2ecyzAMg819PPYf54kF0127uNqesAZBUtVckUZHP32dfUXW9cGsJ3iziBIKBAHQfrNfn80A-S2hwwZFGxKQBqvLxAGn3B-1yj2KTofb99wUySB3rbAB5_6Jqafx0RFKfnfwlEmIT-VRgNTGVekXUSzNw']
2017-12-21 11:29:11,262 [INFO] oauth2client.client: Refreshing access_token
2017-12-22 10:45:13,381 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-22 10:45:13,382 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-22 10:45:13,382 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-22 10:45:13,383 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzOTE3OTEzLCJpYXQiOjE1MTM5MTQzMTN9', 'hFl7ouolhLzJAIC6jHXWvi1IMSQZQVBUqAKVpnfUp8vZnM-j5Me6teKZzMEzSJuNBRPwCqehj98ZzzDGLzv1r5BpmV9Vx3xUW440bpEU7YcoYX1ccvHz0Qdrkaq_DZC9JmgEVHymdeTrRJRl5f_EcZ1lJyjONa1xwkJRljtZW0lBb14iY8rLF1KUTEZqKTrTJj68df3tlyAODi4Mishwp1VYWR6IwTU1fnNULkqMBLZ0fo1BdI8Ak8UNbTQ4LWVgbGLzOKUyEFFR3Wb-m9LdSI0GzPq6jMQQcU27K91MBIbsXC46Fog3Mjwl28WBCFwVGSqb_MDVbA4ELMUI9nP8RA']
2017-12-22 10:45:13,384 [INFO] oauth2client.client: Refreshing access_token
2017-12-22 10:45:18,174 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-22 10:45:18,174 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-22 10:45:18,174 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-22 10:45:18,176 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTEzOTE3OTE4LCJpYXQiOjE1MTM5MTQzMTh9', 'Z9JmNSNDejQ2tbMxcdTkO24g_tzNAUu9sw-OWQScXumHxn-5zx9kqgkABCRsdA35fcyssZCX_IyvSqzyEEuPc_fwK3QNaB8I2XWYerKC8ekwLz60NDy73go3mzsmngVRwXtzRdH89HK2ai6qYqRObIanSbvFe7vXj7PPcG0MgdLUAFi3Xib447hhMmXdhE6U_KHroCphEIIjocda_UIBsaeTabkyvFzro4yxeashKspcmQGr_UF4GAQedtTx1gkE3Qy2K7wuDtKK3fT3uzLAaWaLMaDZ6nuVuLVCoD_mCGw_fBz5XDfT7W4z3mVnzI9va9e40cGmcCBI5JuXKDBQsA']
2017-12-22 10:45:18,176 [INFO] oauth2client.client: Refreshing access_token
2017-12-22 17:53:03,224 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /login/
2017-12-22 17:53:12,029 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /login/
2017-12-23 15:17:50,603 [WARNING] django.request: Forbidden (CSRF cookie not set.): /hndUnblock.cgi
2017-12-23 15:18:01,325 [WARNING] django.request: Forbidden (CSRF cookie not set.): /getcfg.php
2017-12-23 15:18:07,716 [WARNING] django.request: Forbidden (CSRF cookie not set.): /getcfg.php
2017-12-24 03:43:44,490 [ERROR] django.request: Internal Server Error: /storage/
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/edure/edure/views.py", line 284, in storage
    return HttpResponse(json.dumps(resp), content_type='application/json')
UnboundLocalError: local variable 'resp' referenced before assignment
2017-12-24 09:55:22,408 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/edure/edure/views.py", line 198, in home
    return render_to_response('main.html', locals(), context_instance=RequestContext(request))
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/loader.py", line 114, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/engine.py", line 244, in render_to_string
    return t.render(context_instance)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 209, in render
    return template.render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 325, in render
    if match:
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column edure_storage.token does not exist
LINE 1: ..."edure_storage"."files", "edure_storage"."types", "edure_sto...
                                                             ^

2017-12-24 09:55:31,082 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-24 09:55:31,083 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-24 09:55:31,083 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-24 09:55:31,085 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTE0MDg3NzMxLCJpYXQiOjE1MTQwODQxMzF9', 'tGbmXbpYG5qmCqcWcmnn2TcAoWfY6NXP947YMN3_iQCG5KIaDHWw-AW5-NRF7k-ii7Q1uImClXCvUax7-afMbSIZS-9XomGOn4Cl4adzAAhTt9n_zJkDl7t3UFGfjSFyuvh8lQIF6nOJk6SQqaia4nRONW27f5rAcg6ofVbx3Ezz1AMuYndS08HnDa2b1xBMsrmdjFWS6nIwV2malTV7hTZO8H9UPzoye_6AI42R2veLj6bkV2b35F_4faGqgvIQkcoCygeBI1W8m8F72GWRL_ZL5a8SQIKN2uwcTeVDiT5gKYReJuH8NTANv6CVgXzu6uyOJJqBEpCuS5KplQYGWA']
2017-12-24 09:55:31,085 [INFO] oauth2client.client: Refreshing access_token
2017-12-24 09:55:35,901 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-24 09:55:35,902 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-24 09:55:35,902 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-24 09:55:35,904 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTE0MDg3NzM1LCJpYXQiOjE1MTQwODQxMzV9', 'Um4U-PPvfUk7PuGb45FXnLFwv5ryaywnuHVXuK1XCL_KmJjCS8cg_gZTkYbuP6JLHU1oGSvjr9H_36-sdHn8ND7hvlgF-kBUyOFNdV0h7EcUomOp9lQOAJfJ-GBHAiZobXvOaBz1rS7-hOqSf2oLDNkVqMQa8EndWnYggBXmrKGfTokGJ7mAHVnPzNm5I49P3sqffgylznbSgH6rnTSLz_JxBi-nDzx5VO1XeE8NbffoJQd22mCyyqlOqimgeS3h39sdBER5R5iKbSs4kgzgZgxh4f3v6bvqtrmYg00Inkzm1GNYmV9mz1uwYoTKdUNi4H6-0KI03eQlN__dz1KLwA']
2017-12-24 09:55:35,904 [INFO] oauth2client.client: Refreshing access_token
2017-12-24 14:17:11,322 [ERROR] django.request: Internal Server Error: /file_manager/library/19
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/edure/edure/views.py", line 339, in file_manager_library
    parent = Storage.objects.get(id=key)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column edure_storage.ext does not exist
LINE 1: ..."edure_storage"."files", "edure_storage"."types", "edure_sto...
                                                             ^

2017-12-24 14:17:20,737 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-24 14:17:20,739 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-24 14:17:20,739 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-24 14:17:20,741 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTE0MTAzNDQwLCJpYXQiOjE1MTQwOTk4NDB9', 'PBpDcaUyG5AcssLQ4h9BJ2vg7LKjt_avCQhyfqFRTm0SPIh-1mNwe2hL8Ifrsy8Opg2uya6C7ZsmPdDt8I0vc2hiT70hhVMY015j2ywGhjlZTseSvt6lmKfSD-7wnmk_RM1J89F2K_yHXzMjxEgZAFXalz1WZO7y7kcdX3QTTkdLUBTa15WZtS_OjL2op1sCwxdnLLIR5Z-DbES-i5UV8Zdw5rsA1HO_h9j0S1RIjerAADOrgFlL-9mf2jA_uDQi4ugA_RzihzISTQZb16bCOieiU9ZOdTgN9PrYBWiWuZqw8kAo1ElWp1-SnMl78HX_MKfJUDiuvQlQx1veowV5lw']
2017-12-24 14:17:20,741 [INFO] oauth2client.client: Refreshing access_token
2017-12-24 14:17:25,583 [WARNING] googleapiclient.discovery_cache: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/ubuntu/edure_env/local/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2017-12-24 14:17:25,584 [INFO] googleapiclient.discovery: URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2017-12-24 14:17:25,584 [INFO] oauth2client.transport: Attempting refresh to obtain initial access_token
2017-12-24 14:17:25,586 [DEBUG] oauth2client.crypt: ['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgxZTEwN2MwNTk4OTY3ZTA4ODIxZTAxYzY0ZWY3NWRmZjM3OGExMzIifQ', 'eyJpc3MiOiJlZHVyZS00MTNAdmlydHVhbC1hbmNob3ItMTg5MzAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIiwiYXVkIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwiZXhwIjoxNTE0MTAzNDQ1LCJpYXQiOjE1MTQwOTk4NDV9', 'cxnHXb2pUICXD0tr7UqysnZWTLl9LBxTmdqXfqY70K7Vo1FQ02GF3l2MVIXhJHvbMJiJMn3rPIDgLcwfaQCUDClzFE5vXwm1TmKQ3vyfey9cDBE3KqqUomFo9jPRwmrx3jafCylvJj3Sg-cKUX9sJtu5vbTyF3YzyUOgc0ZEAllMGtR2mb_u7pUUynVsOUv0FkFfCXm_zXiF6GMdIgWGiaR8hOj-J3MT4eqXDHcd3B82r48a_3_vD4coKDSuHPRbdfVB0rUyy49kRLvliaDUmzrX5R2aJrthSvrfl3mvxmPnYwlog5xgtu-8oPFYjAgwKZI5Jxu298z8hjO8s9gnyw']
2017-12-24 14:17:25,586 [INFO] oauth2client.client: Refreshing access_token
2018-03-23 11:01:43,258 [WARNING] django.request: Forbidden (CSRF cookie not set.): /wp-admin/admin-ajax.php
2018-03-26 09:48:21,534 [WARNING] django.request: Forbidden (CSRF cookie not set.): /RPC2
2018-03-27 20:55:15,036 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /admin/login/
2018-03-27 20:55:25,406 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /admin/login/
2018-03-27 20:55:33,491 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /admin/login/
2018-03-27 20:56:43,589 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /login/
2018-03-27 20:57:02,431 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /login/
2018-03-27 20:58:07,905 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /login/
2018-03-28 19:14:25,945 [WARNING] django.request: Forbidden (CSRF cookie not set.): /command.php
2018-03-29 04:17:29,573 [WARNING] django.request: Forbidden (CSRF cookie not set.): /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2018-03-29 08:17:29,951 [WARNING] django.request: Forbidden (CSRF cookie not set.): /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2018-03-29 13:11:51,876 [WARNING] django.request: Forbidden (CSRF cookie not set.): /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2018-03-30 17:40:43,599 [WARNING] django.request: Forbidden (CSRF cookie not set.): /login/
2018-06-06 17:07:29,374 [WARNING] django.request: Forbidden (CSRF cookie not set.): /login/
2018-06-06 17:13:30,633 [WARNING] django.request: Forbidden (CSRF cookie not set.): /login/
2018-06-06 17:13:53,188 [WARNING] django.request: Forbidden (CSRF cookie not set.): /login/
